spring:
  application:
    name: reserva-vuelos


  datasource:
    url: jdbc:postgresql://localhost:5432/basedatos
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8085
